Ericsson/ecaudit

- README.md
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITVerifyAudit.java
USE statements will appear twice in the audit log.
Timestamp of second appearance may be wrong.
> Verify and document behavior of USE statement

- CHANGES.md
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditRoleManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistManager.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditRoleManager.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditWhitelistManager.java
Make AuditRoleManager a decorator of CassandraRoleManager instead of extending it.
This make ARM more testable without bringing in all the runtime dependencies of CRM.
Also make audit whitelist tables a protected resource to prevent manual tampering.
>  Improve unit test coverage on AuditRoleManager

- CHANGES.md
- doc/setup.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditPasswordAuthenticator.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditYamlConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditYamlSlf4jConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/AuditEntry.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/handler/AuditQueryHandler.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/Slf4jAuditLogger.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/TestAuditAdapter.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditPasswordAuthenticator.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/config/TestAuditYamlConfigurationLoader.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/entry/TestAuditEntry.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/handler/TestAuditQueryHandler.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/logger/TestSlf4jAuditLogger.java
- ecaudit/src/test/resources/mock_log_format.yaml
- integration-test-custom-format/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/custom/ITVerifyCustomLogFormat.java
- integration-test-custom-format/src/test/resources/integration_audit.yaml
Also restructure the audit.yaml file so that logFormat, timeFormat and timeZone
are configured inside a slf4j section.
Closes #27
> Add timestamp field to custom log format

- doc/setup.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditYamlConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditYamlSlf4jConfig.java
- ecaudit/src/test/resources/mock_log_format.yaml
- integration-test-custom-format/src/test/resources/integration_audit.yaml
Rename new log formatting parameters to get same look and fell as Cassandra yaml file:
---
slf4j:
logFormat -> log_format
timeFormat -> time_format
timeZone -> time_zone
Closes #67
> Use snake_case instead of camelCase for yaml config parameters

- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/Exceptions.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/SchemaHelper.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistDataAccess.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/TestAuditAdapter.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestExceptions.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestSchemaHelper.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/role/TestRoleAuditFilter.java
This way queries on the whitelist table will be valid across the cluster once CQL queries are received.
Also, make sure to wrap request exceptions in an authentication exception for authentication audits.
Otherwise the client will be confused.
Closes #57
> Wait for schema alignment when audit whitelist table is created

- CHANGES.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/metrics/AuditMetrics.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/metrics/TestAuditMetrics.java
Added timers for how long time it takes to both filter and
log audit entries. These metrics are exposed over JMX as well.
Fixes #72.
> Add timer metrics for auditing

- pom.xml
The EXPERIMENTAL_NAKED_RECEIVER mutator works well for code contaning
e.g. the builder patterns and the streams api (java8).
> Configure pitest with naked receiver mutator

- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/suppressor/AbstractSuppressor.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/utils/Strings.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/entry/suppressor/TestSuppressBlobs.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/entry/suppressor/TestSuppressRegular.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/utils/TestStrings.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/custom/ITVerifyCustomBoundValueSuppressor.java
Frozen brackets are printed for frozen datatypes in column suppressors:
`map<int, frozen<list<blob>>>
`
This change removed the frozen brackets so that only the data types are printed:
`map<int, list<blob>>`
> Remove frozen-brackets from suppressed column data types

- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistCache.java
Catching checked exception in AuditWhitelistCache to be campatible with 3.11.2 - 3.11.4.
> Restore 3.11.2 compatibility

- CHANGES.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/factory/AuditEntryBuilderFactory.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/custom/ITVerifyCustomLogFormat.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/custom/ITVerifyPostLogging.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyThreadedAudit.java
Previous tests assumed normal batches containing prepared statements.
Fixes #164
Tries to align it with log entries from Apache Cassandra 4.0:
```
INFO  [Native-Transport-Requests-1] 2020-04-07 13:39:04,545 FileAuditLogger.java:49 - user:anonymous|host:127.0.0.1:7000|source:/127.0.0.1|port:34212|timestamp:1586259544538|type:BATCH|category:DML|operation:BEGIN UNLOGGED BATCH USING TIMESTAMP ? INSERT INTO ecks.ectbl (partk, clustk, value) VALUES (?, ?, ?); INSERT INTO ecks.ectbl (partk, clustk, value) VALUES (?, ?, 'valid'); APPLY BATCH;
```
Even though it is slightly different compared to the batches currently handled.
> Add support for prepared batch statements

- CHANGES.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/AuditFilterAuthorizer.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/role/TestAuditFilterAuthorizer.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/CassandraClusterFacade.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITRolesAudit.java
While connecting the driver will perform select on a few tables
without explicit permission. Since the user is allowed we should
not log these statements when grant based is configured.
Fixes  #172 for C2.2
> Extend grant based audit to system tables

- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/PreparedAuditOperation.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/handler/AuditQueryHandler.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/handler/TestAuditQueryHandler.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyAudit.java
This does not seem to affect the 3.0 branch as the statements are not [cached without the raw CQL statement during startup](https://github.com/apache/cassandra/blob/cassandra-3.11/src/java/org/apache/cassandra/cql3/QueryProcessor.java#L160).
The patch handles this by requesting the client to prepare the statement again whenever a prepared statement is cached without the raw CQL statement.
Fixes #193
> Reprepare statements that are loaded during startup

- pom.xml
The thrift dependecy should have been removed since its not part of Cassandra 4.0
> Clean up pom.xml

- README.md
- UPGRADING.md
Update the upgrade guide to prepare for ecAudit 3.0.0 with Cassandra 4.1 support.
> Update upgrade guide

- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/ConnectionResource.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistOptionParser.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/suppressor/SuppressBlobs.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/FileQueueBootstrapper.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/SizeRotatingStoreFileListener.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/Slf4jAuditLogger.java
- pom.xml
> Step maven-pmd-plugin version to support java17

- CONTRIBUTING.md
- README.md
- doc/cassandra_compatibility.md
> Prepare documantation for the new release/c4.1 branch

- .github/workflows/test.yml
- common/pom.xml
- ecaudit/pom.xml
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/CqlLiteralFlavorAdapter.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestSchemaHelper.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestWhitelistOptionParser.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/entry/TestCqlLiteralFlavorAdapter.java
- eclog/pom.xml
- integration-test-allow-all-authorizer/pom.xml
- integration-test-query-logger/pom.xml
- integration-test-standard/pom.xml
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyWhitelistManagement.java
- pom.xml
- test-utils/pom.xml
- test-utils/src/main/java/com/ericsson/bss/cassandra/ecaudit/test/mode/ClientInitializer.java
Closes #223 
Closes #224 
Closes #225
> cassandra 5 support

- CHANGES.md
- conf/audit.yaml
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditYamlConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/suppressor/PrepareAuditOperation.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/Auditor.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/AuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/yaml/YamlAuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/yamlandrole/YamlAndRoleAuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/handler/AuditQueryHandler.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/config/TestAuditYamlConfigurationLoader.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/handler/TestAuditQueryHandler.java
- ecaudit/src/test/resources/mock_configuration.yaml
- integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/ITQueryLogger.java
- integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/PrepareAuditQueryLogger.java
- integration-test-query-logger/src/test/resources/integration_audit.yaml
- test-utils/src/main/java/com/ericsson/bss/cassandra/ecaudit/test/mode/ClientInitializer.java
> Audit prepare statements (#226)

- CHANGES.md
- conf/audit.yaml
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditYamlConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/suppressor/PrepareAuditOperation.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/Auditor.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/AuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/yaml/YamlAuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/yamlandrole/YamlAndRoleAuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/handler/AuditQueryHandler.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/config/TestAuditYamlConfigurationLoader.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/handler/TestAuditQueryHandler.java
- ecaudit/src/test/resources/mock_configuration.yaml
- integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/ITQueryLogger.java
- integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/PrepareAuditQueryLogger.java
- integration-test-query-logger/src/test/resources/integration_audit.yaml
- test-utils/src/main/java/com/ericsson/bss/cassandra/ecaudit/test/mode/ClientInitializer.java
> #226 Audit Prepare statements 

- osv-scanner.toml
- pom.xml
Since we use SnakeYaml's SafeConsturctor we are not affected.
#246
> Ignore GHSA-mjmj-j48q-9wg2

- .github/workflows/test.yml
We need to update all github/actions to versions that support Node 20 since Node 16 is deprecated, for more info see
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
> Update versions of github/actions in workflow
