- README.md
Also give instructions on how to get documentation for specific versions
> Update README with references to Maven Central

- .travis.yml
- README.md
- pom.xml
Adding coverage badge to README
Restoring original colors of maven release to indicate zero major version
> Configure JaCoCo coverage and report to Coveralls

- .idea/codeStyleSettings.xml
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/misc.xml
- CONTRIBUTING.md
>  Include code style settings for Intellij in the repo

- pom.xml
> Bump java-driver version to 3.6.0

- CHANGES.md
- pom.xml
- src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapterFactory.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/Slf4jAuditLogger.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/obfuscator/PasswordObfuscator.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/TestAuditAdapterFactory.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/role/TestRoleAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITVerifyAudit.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITVerifyThreadedAudit.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITVerifyWhitelistManagement.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/logger/TestSlf4jAuditLogger.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/microbench/BenchmarkSlf4jAuditLogger.java
Adding JMH micro benchmark framework.
Fixing typos.
Renaming FileAuditLogger to Slf4jAuditLogger.
> Optimize logger using micro benchmark

- pom.xml
- src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapter.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditPasswordAuthenticator.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/Status.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/obfuscator/PasswordObfuscator.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/TestAuditAdapter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestConnectionResource.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/role/TestRoleAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/obfuscator/TestPasswordObfuscator.java
Also improving line test coverage
> Improve PIT Mutation test coverage

- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditAuthKeyspace.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditPasswordAuthenticator.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditRoleManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistCache.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/ConnectionResource.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/ResourceFactory.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistDataAccess.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditPasswordAuthenticator.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditWhitelistManager.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestResourceFactory.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/role/TestRoleAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITVerifyWhitelistManagement.java
> Factor out a Resource factory

- bin/install_into_current_ccm.sh
> Add ccm setup script for ecAudit

- src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/AuditEntry.java
Removed obvious comments.
Elaborated on non-obvious behavior.
> Cleanup javadoc of AuditEntry

- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistContract.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistOperation.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistOptionParser.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditWhitelistManager.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestWhitelistContract.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestWhitelistOptionParser.java
In preparation for improved operation filter.
> Refactor Whitelist Manager

- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditRoleManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/ResourceFactory.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistDataAccess.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditWhitelistManager.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestResourceFactory.java
In preparation for improved operation filter.
Consistent interface with IResource type for whitelist resources in the interface.
consistent interface with RoleResource type for grantee in the interface.
> Refactor Whitelist data access

- src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapter.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapterFactory.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditAuthorizer.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditPasswordAuthenticator.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditRoleManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistCache.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistDataAccess.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/Auditor.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/AuditFilter.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/DefaultAuditFilter.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/yaml/YamlAuditFilter.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/yamlandrole/YamlAndRoleAuditFilter.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/handler/AuditQueryHandler.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/Slf4jAuditLogger.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/TestAuditAdapter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/TestAuditAdapterFactory.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditPasswordAuthenticator.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditWhitelistManager.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/TestDefaultAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/role/TestRoleAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/yaml/TestYamlAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/yamlandrole/TestYamlAndRoleAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/CassandraDaemonForAuditTest.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/logger/TestSlf4jAuditLogger.java
Replacing some statics with singletons
This enables some more mocking with improved test coverage
This also makes wiring of components and setup more robust
> Improve startup wiring and testability

- CHANGES.md
- UPGRADING.md
- doc/role_whitelist_management.md
- pom.xml
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditAuthKeyspace.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditRoleManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistCache.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditWhitelistManager.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/OperationFactory.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/ResourceFactory.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistContract.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistDataAccess.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistOptionParser.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/AuditEntry.java
- src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditWhitelistManager.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestOperationFactory.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestResourceFactory.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestWhitelistContract.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestWhitelistOptionParser.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/role/TestRoleAuditFilter.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITDataAudit.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITFunctionsAudit.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITRolesAudit.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITVerifyAudit.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITVerifyThreadedAudit.java
- src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/ITVerifyWhitelistManagement.java
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Align look-and-feel in ALTER ROLE statement and LIST ROLES statements.
> Upgrade procedure for operation filter

- bin/install_into_current_ccm.sh
- bin/prep_current_ccm_for_performance_smoke_test.sh
CCM_CONFIG_DIR environment variable specifies the directory for the cluster files.
In case it is set, use that directory when installing ecaudit.
> Update CCM install script to handle custom directory

- pom.xml
Temporary workaround for issue #63
> Disable custom log format integration test

- common/src/main/java/com/ericsson/bss/cassandra/ecaudit/common/chronicle/AuditRecordWriteMarshallable.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/PermissionChecker.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/SchemaHelper.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistDataAccess.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
Utilize streams to simplify code...
> Refactoring to simplify code

- common/src/test/java/com/ericsson/bss/cassandra/ecaudit/common/chronicle/TestReadVersion0.java
- common/src/test/java/com/ericsson/bss/cassandra/ecaudit/common/chronicle/TestWriteReadVersionCurrent.java
- common/src/test/java/com/ericsson/bss/cassandra/ecaudit/common/chronicle/WriteTestDataUtil.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditPasswordAuthenticator.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/ConnectionResource.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/PermissionChecker.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/cache/AuthCache.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/cache/AuthCacheMBean.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditYamlConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/factory/AuditEntryBuilderFactory.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/factory/StatementResourceAdapter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/ChronicleAuditLoggerConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/SizeRotatingStoreFileListener.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/Slf4jAuditLogger.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/metrics/AuditMetrics.java
- ecaudit/src/microbench/java/com/ericsson/bss/cassandra/ecaudit/logger/BenchmarkChronicleAuditLogger.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/TestAuditAdapterFactory.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/config/TestAuditYamlConfigurationLoader.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/entry/TestPreparedAuditOperation.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/role/TestRoleAuditFilter.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/handler/TestAuditQueryHandler.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/logger/TestToStringer.java
- eclog/src/test/java/com/ericsson/bss/cassandra/ecaudit/eclog/TestOptionParser.java
- integration-test-chronicle/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/chronicle/ITVerifyChronicleBackend.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITDataAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITFunctionsAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITRolesAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyThreadedAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyWhitelistManagement.java
* method/variable scope
* unused imports
* constants/final variables
* generics
* exceptions declared but never thrown
* unnecessary boxing
> Fix Idea inspection warnings

- .travis.yml
- CONTRIBUTING.md
- common/pom.xml
- ecaudit/pom.xml
- eclog/pom.xml
- integration-test-chronicle/pom.xml
- integration-test-custom-format/pom.xml
- integration-test-post-logging/pom.xml
- integration-test-standard/pom.xml
- pmd-rules.xml
- pom.xml
- test-utils/pom.xml
Add some guidelines in the contributors guide
> Improve CI speed

- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistDataAccess.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestWhitelistDataAccess.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITDataAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyWhitelistManagement.java
User prepared statements for traffic requests in whitelist DAO
Closes #43
> Align WhitelistDataAccess statements

- CHANGES.md
- conf/audit.yaml
- doc/cassandra_compatibility.md
- doc/setup.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/AuditAdapter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditAuthorizer.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/WhitelistOptionParser.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/config/AuditYamlConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/ChronicleAuditLoggerConfig.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/utils/Exceptions.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditAuthorizer.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/config/TestAuditYamlConfigurationLoader.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/utils/TestExceptions.java
- integration-test-allow-all-authorizer/pom.xml
- integration-test-allow-all-authorizer/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/allowallauthorizer/ITAllowAllAuthorizer.java
- integration-test-allow-all-authorizer/src/test/resources/cassandra-rackdc.properties
- integration-test-allow-all-authorizer/src/test/resources/cassandra.yaml
- integration-test-allow-all-authorizer/src/test/resources/integration_audit.yaml
- integration-test-allow-all-authorizer/src/test/resources/logback.xml
- pom.xml
> Make wrapped authorizer backend configurable

- ecaudit/pom.xml
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/TestAuditAdapter.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/TestAuditAdapterFactory.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditAuthorizer.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditRoleManager.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestAuditWhitelistManager.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestPermissionChecker.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/auth/TestSchemaHelper.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/handler/TestAuditQueryHandler.java
- pom.xml
- test-utils/src/main/java/com/ericsson/bss/cassandra/ecaudit/test/mode/ClientInitializer.java
> Isolate unit test differences in branches

- .travis.yml
This will fix broken build with Java 8.
> Build on travis with Ubuntu trusty

- CHANGES.md
- doc/cassandra_compatibility.md
- ecaudit/pom.xml
- eclog/pom.xml
- integration-test-standard/pom.xml
- pom.xml
Move slf4j dependency into eclog.
Bump some other versions as well.
> Bump Cassandra version to 2.2.15

- bin/import_cassandra_yaml_to_it.sh
- integration-test-allow-all-authorizer/src/test/resources/cassandra.yaml
- integration-test-standard/src/test/resources/cassandra.yaml
> Disable auto_snapshot in integration tests

- integration-test-standard/pom.xml
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/CassandraAuditTester.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/CassandraClusterFacade.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITDataAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITDataPreparedAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITFunctionsAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITRolesAudit.java
Introduce JUnitParamsRunner so that the statements to be tested
(for data/functions/roles) can be reused for different type of
whiltelistings.
> Refactor IT to be reuseable

- CHANGES.md
- doc/cassandra_compatibility.md
- doc/install.md
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/custom/ITVerifyCustomBoundValueSuppressor.java
- pom.xml
> Bump Cassandra version

- pom.xml
Reducing the number of steps when performing release.
> Enable auto version of submodules

- CONTRIBUTING.md
- README.md
- doc/cassandra_compatibility.md
Update doc and guidelines to reflect this.
> Drop feature development on 3.0.11 flavor

- doc/role_whitelist_management.md
Also referred to as "Access Derived Whitelisting"
> Documentation for grants-based role whitelisting

- bin/configure_ccm_audit_chronicle.sh
- bin/configure_ccm_audit_slf4j.sh
- bin/run_ccm_performance_test.sh
Add dummy tables and dummy whitelist configuration to get a more
realistic performance measurements for the whitelist scenarios.
Added measurement for:
- yaml (file) based whitelisting
- permission derived role whitelisting
> Update performance tests

- CHANGES.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/AuditEntry.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/factory/AuditEntryBuilderFactory.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/obfuscator/PasswordObfuscator.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/obfuscator/TestPasswordObfuscator.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyAudit.java
> Obfuscate passwords properly

- common/pom.xml
- ecaudit/pom.xml
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilterCache.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/facade/TestDefaultAuditor.java
- eclog/pom.xml
- integration-test-allow-all-authorizer/pom.xml
- integration-test-query-logger/pom.xml
- integration-test-standard/pom.xml
- pom.xml
- test-utils/pom.xml
Audit a record even if there is an exception while fetching whitelist role from table.
Fixes #168
> Schema version mismatch detected in Kubernetes Cluster #168

- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/facade/DefaultAuditor.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilter.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/filter/role/RoleAuditFilterCache.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/utils/Exceptions.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/filter/role/TestRoleAuditFilter.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/utils/TestExceptions.java
> Tune exception handling in role based whitelist filter

- CHANGES.md
- eclog/pom.xml
> Bump to SnakeYAML 1.29 in eclog

- CHANGES.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/factory/AuditEntryBuilderFactory.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/factory/StatementResourceAdapter.java
> ALTER KEYSPACE statement is treated as unrecognized

- CHANGES.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/entry/factory/AuditEntryBuilderFactory.java
> Support server side DESCRIBE command in 4.0

- CHANGES.md
- doc/slf4j_logger.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/Slf4jAuditLogger.java
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/logger/Slf4jAuditLoggerConfig.java
- ecaudit/src/test/java/com/ericsson/bss/cassandra/ecaudit/logger/TestSlf4jAuditLogger.java
> Add support for escaping characters in slf4j

- .github/workflows/test.yml
- CHANGES.md
- doc/setup.md
- integration-test-allow-all-authorizer/pom.xml
- integration-test-query-logger/pom.xml
- integration-test-standard/pom.xml
> Test c4.0 with java11

- integration-test-allow-all-authorizer/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/allowallauthorizer/ITAllowAllAuthorizer.java
- integration-test-query-logger/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/querylogger/ITQueryLogger.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/custom/ITVerifyChronicleBackend.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/custom/ITVerifyCustomBoundValueSuppressor.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/custom/ITVerifyCustomLogFormat.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/custom/ITVerifyPostLogging.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/CassandraClusterFacade.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITDataAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITDataPreparedAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITFunctionsAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITRolesAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyThreadedAudit.java
- integration-test-standard/src/test/java/com/ericsson/bss/cassandra/ecaudit/integration/standard/ITVerifyWhitelistManagement.java
- pom.xml
- test-utils/pom.xml
- test-utils/src/main/java/com/ericsson/bss/cassandra/ecaudit/test/daemon/CassandraDaemonForAuditTest.java
> Step to java-driver 4.16.0

- .github/workflows/test.yml
- pom.xml
> Add test with java build target 11

- CHANGES.md
- common/pom.xml
- ecaudit/pom.xml
- eclog/pom.xml
- integration-test-allow-all-authorizer/pom.xml
- integration-test-query-logger/pom.xml
- integration-test-standard/pom.xml
- pom.xml
- test-utils/pom.xml
> Align versions across the flavours

- .github/workflows/test.yml
>  Merge branch 'release/c3.0' into release/c3.11 

- CODEOWNERS
- pom.xml
> Add codeowners to this repo

- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/SchemaHelper.java
> Fix Implicit narrowing conversion in compound

- common/pom.xml
- common/src/main/java/com/ericsson/bss/cassandra/ecaudit/common/chronicle/AuditRecordReadMarshallable.java
- common/src/main/java/com/ericsson/bss/cassandra/ecaudit/common/chronicle/AuditRecordWriteMarshallable.java
- ecaudit/pom.xml
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/ConnectionResource.java
- eclog/src/test/java/com/ericsson/bss/cassandra/ecaudit/eclog/TestLogPrinter.java
- pom.xml
> Remove org.jetbrains.annotations dependency

- CHANGES.md
- pom.xml
> Step commons-cli to version 1.6.0

- doc/cassandra_compatibility.md
> Update compatibility doc

- CHANGES.md
- doc/cassandra_compatibility.md
- pom.xml
> Build with Cassandra 5.0.0

- CHANGES.md
- ecaudit/src/main/java/com/ericsson/bss/cassandra/ecaudit/auth/AuditAuthorizer.java
- pom.xml
This fix will work with Cassandra 5.0.0 and newer.
Closes #274
> Fix build error with Cassandra 5.0.2
